name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Download NLTK Data
      run: |
        python -m nltk.downloader averaged_perceptron_tagger wordnet omw-1.4 punkt

    - name: Run Unit Tests
      run: |
        python -m unittest discover backend/tests
